/**
 * CANONICAL BRANDING CONSTANTS
 * ─────────────────────────────────────────────────────────
 * Single source of truth for all branding defaults across the platform.
 * Every component, PDF generator, email template, and API route
 * MUST reference these constants instead of hardcoding colors/values.
 *
 * @see MASTER_HARDENING_AUDIT.md — BRAND-001, BRAND-002
 */

// ─── Platform Brand Colors ────────────────────────────────
/** The canonical SkaiScraper brand blue — use this everywhere */
export const BRAND_PRIMARY = "#117CFF";
/** Dark navy for backgrounds, headers, dark-mode text */
export const BRAND_NAVY = "#0A1A2F";
/** Accent gold — CTAs, highlights */
export const BRAND_ACCENT = "#FFC838";
/** Secondary sky blue */
export const BRAND_SECONDARY = "#0EA5E9";

// ─── Fallback Colors (when org hasn't set branding) ───────
export const DEFAULT_COLORS = {
  /** Default primary brand color for new orgs */
  primary: BRAND_PRIMARY,
  /** Default accent color */
  accent: BRAND_ACCENT,
  /** Default secondary color */
  secondary: BRAND_SECONDARY,
  /** Default dark background color */
  navy: BRAND_NAVY,
  /** Default text color */
  text: "#0f172a",
} as const;

// ─── RGB Tuples (for jsPDF / canvas contexts) ─────────────
/** #117CFF as [R, G, B] */
export const BRAND_PRIMARY_RGB: [number, number, number] = [17, 124, 255];
/** #0A1A2F as [R, G, B] */
export const BRAND_NAVY_RGB: [number, number, number] = [10, 26, 47];

// ─── Platform Identity ───────────────────────────────────
export const PLATFORM_NAME = "SkaiScraper";
export const PLATFORM_DOMAIN = "skaiscrape.com";
export const PLATFORM_URL = "https://skaiscrape.com";
export const PLATFORM_TAGLINE = "Storm restoration intelligence, simplified.";
export const PLATFORM_EMAIL_FROM = `${PLATFORM_NAME} <notifications@${PLATFORM_DOMAIN}>`;

// ─── PDF Footer/Header Defaults ──────────────────────────
export const PDF_HEADER_DEFAULT = `${PLATFORM_NAME} Report`;
export const PDF_FOOTER_DEFAULT = `Generated by ${PLATFORM_NAME}`;
export const PDF_POWERED_BY = `Powered by ${PLATFORM_NAME}`;

// ─── Branding Completeness Check ─────────────────────────
/** Canonical definition of "branding is complete" — ONE check, used everywhere */
export function isBrandingComplete(branding: {
  companyName?: string | null;
  logoUrl?: string | null;
  phone?: string | null;
  email?: string | null;
}): boolean {
  return Boolean(
    branding.companyName?.trim() &&
    branding.logoUrl?.trim() &&
    branding.phone?.trim() &&
    branding.email?.trim()
  );
}

// ─── Default Branding Shape ──────────────────────────────
export interface BrandingDefaults {
  companyName: string;
  phone: string;
  email: string;
  website: string;
  logoUrl: string;
  colorPrimary: string;
  colorAccent: string;
  tagline: string;
}

/** The fallback branding object when org has no branding configured */
export const EMPTY_BRANDING: BrandingDefaults = {
  companyName: "",
  phone: "",
  email: "",
  website: "",
  logoUrl: "",
  colorPrimary: BRAND_PRIMARY,
  colorAccent: BRAND_ACCENT,
  tagline: "",
};
