/**
 * ClaimIQ™ — Assembly Engine
 *
 * The "Evidence Orchestrator" — connects the four layers:
 *   1. Computer Vision (YOLO detections)
 *   2. Claim Intelligence (weather + event correlation)
 *   3. Documentation (17-section packet)
 *   4. Contractor Workflow (claim workspace)
 *
 * For each of the 17 sections it determines:
 *   - What data is available
 *   - What's missing
 *   - Whether the section can auto-fill
 *   - What the pro needs to do next
 *
 * This is the brain that turns "upload photos" into "full packet writes itself."
 */

import { logger } from "@/lib/logger";
import prisma from "@/lib/prisma";

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export type SectionStatus = "ready" | "partial" | "missing" | "manual";

export interface SectionReadiness {
  key: string;
  label: string;
  number: number;
  required: boolean;
  status: SectionStatus;
  /** 0-100 — how much data is available for this section */
  completeness: number;
  /** What data sources are available */
  availableSources: string[];
  /** What's still missing */
  missingItems: string[];
  /** Human-readable next action for the pro */
  nextAction: string | null;
  /** Can this section be auto-generated by AI? */
  canAutoGenerate: boolean;
  /** Has this section already been generated? */
  hasExistingContent: boolean;
}

export interface ClaimIQReadiness {
  claimId: string;
  overallScore: number; // 0-100
  overallGrade: "A" | "B" | "C" | "D" | "F";
  sections: SectionReadiness[];
  /** Counts */
  readySections: number;
  partialSections: number;
  missingSections: number;
  /** Actionable summary */
  topActions: string[];
  /** Data layer status */
  layers: {
    vision: { ready: boolean; photoCount: number; detectionCount: number };
    weather: { ready: boolean; hasVerification: boolean };
    documentation: { ready: boolean; generatedDocs: number };
    workflow: { ready: boolean; claimStatus: string };
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Section Definitions (the 17 sections)
// ─────────────────────────────────────────────────────────────────────────────

const SECTION_DEFS: Array<{
  key: string;
  label: string;
  number: number;
  required: boolean;
  canAutoGenerate: boolean;
}> = [
  { key: "cover-sheet", label: "Cover Sheet", number: 1, required: true, canAutoGenerate: true },
  {
    key: "table-of-contents",
    label: "Table of Contents",
    number: 2,
    required: false,
    canAutoGenerate: true,
  },
  {
    key: "executive-summary",
    label: "Executive Summary",
    number: 3,
    required: true,
    canAutoGenerate: true,
  },
  {
    key: "weather-cause-of-loss",
    label: "Weather & Cause of Loss",
    number: 4,
    required: true,
    canAutoGenerate: true,
  },
  {
    key: "inspection-overview",
    label: "Inspection Overview",
    number: 5,
    required: true,
    canAutoGenerate: true,
  },
  { key: "damage-grids", label: "Damage Grids", number: 6, required: false, canAutoGenerate: true },
  {
    key: "photo-evidence",
    label: "Photo Evidence",
    number: 7,
    required: true,
    canAutoGenerate: true,
  },
  {
    key: "code-compliance",
    label: "Code Compliance",
    number: 8,
    required: true,
    canAutoGenerate: true,
  },
  {
    key: "scope-pricing",
    label: "Scope & Pricing",
    number: 9,
    required: true,
    canAutoGenerate: false,
  },
  {
    key: "repair-justification",
    label: "Repair Justification",
    number: 10,
    required: true,
    canAutoGenerate: true,
  },
  {
    key: "contractor-summary",
    label: "Contractor Summary",
    number: 11,
    required: true,
    canAutoGenerate: true,
  },
  { key: "timeline", label: "Timeline", number: 12, required: false, canAutoGenerate: true },
  {
    key: "homeowner-statement",
    label: "Homeowner Statement",
    number: 13,
    required: false,
    canAutoGenerate: false,
  },
  {
    key: "adjuster-cover-letter",
    label: "Adjuster Cover Letter",
    number: 14,
    required: false,
    canAutoGenerate: true,
  },
  {
    key: "claim-checklist",
    label: "Claim Checklist",
    number: 15,
    required: false,
    canAutoGenerate: true,
  },
  {
    key: "digital-signatures",
    label: "Digital Signatures",
    number: 16,
    required: false,
    canAutoGenerate: false,
  },
  { key: "attachments", label: "Attachments", number: 17, required: false, canAutoGenerate: true },
];

// ─────────────────────────────────────────────────────────────────────────────
// Main Engine
// ─────────────────────────────────────────────────────────────────────────────

export async function assessClaimReadiness(
  claimId: string,
  orgId: string
): Promise<ClaimIQReadiness> {
  const startTime = Date.now();

  // ── Parallel data fetch (one DB round-trip per concern) ────────────────
  const [
    claim,
    weatherReport,
    photos,
    analyzedPhotos,
    codeItems,
    scopeItems,
    supplements,
    signatures,
    activities,
    documents,
    org,
  ] = await Promise.all([
    // Claim + property
    prisma.claims.findFirst({
      where: { id: claimId, orgId },
      include: {
        properties: {
          select: {
            street: true,
            city: true,
            state: true,
            zipCode: true,
            roofType: true,
            roofAge: true,
            contacts: { select: { firstName: true, lastName: true } },
          },
        },
      },
    }),
    // Weather
    prisma.weather_reports.findFirst({
      where: { claimId },
      orderBy: { createdAt: "desc" },
    }),
    // All photos
    prisma.file_assets.count({
      where: { orgId, claimId, category: "photo" },
    }),
    // Analyzed photos (with YOLO detections)
    prisma.file_assets.count({
      where: { orgId, claimId, category: "photo", analyzed_at: { not: null } },
    }),
    // Code compliance items
    prisma.code_requirements.count({
      where: { orgId },
    }),
    // Scope items (check if scope_areas or scope_line_items exist)
    prisma.file_assets.count({
      where: { orgId, claimId, file_type: "ESTIMATE" },
    }),
    // Supplements
    prisma.claim_supplements.count({
      where: { claim_id: claimId },
    }),
    // Digital signatures
    prisma.file_assets.count({
      where: { orgId, claimId, file_type: "SIGNATURE" },
    }),
    // Timeline events (activities)
    prisma.claim_activities.count({
      where: { claim_id: claimId },
    }),
    // Generated documents
    prisma.file_assets.findMany({
      where: { orgId, claimId, category: "document" },
      select: { file_type: true, source: true },
    }),
    // Org profile
    prisma.org.findUnique({
      where: { id: orgId },
      select: { name: true, brandLogoUrl: true },
    }),
  ]);

  // ── Build derived facts ────────────────────────────────────────────────
  const hasClaim = !!claim;
  const hasProperty = !!claim?.properties;
  const hasAddress = !!(claim?.properties?.street && claim?.properties?.city);
  const hasInsuredName = !!(claim?.insured_name || claim?.properties?.contacts?.firstName);
  const hasCarrier = !!claim?.carrier;
  const hasDateOfLoss = !!claim?.dateOfLoss;
  const hasPolicyNumber = !!claim?.policy_number;

  const hasWeather = !!weatherReport;
  const hasWeatherNarrative = !!weatherReport?.overallAssessment;
  const hasWeatherEvents =
    Array.isArray(weatherReport?.events) && (weatherReport?.events as unknown[]).length > 0;

  const hasPhotos = photos > 0;
  const hasAnalyzedPhotos = analyzedPhotos > 0;
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const photoCompleteness = photos >= 10 ? 100 : photos >= 5 ? 75 : photos >= 1 ? 40 : 0;

  const hasCodes = codeItems > 0;
  const hasScope = scopeItems > 0;
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const hasSupplements = supplements > 0;
  const hasSignatures = signatures > 0;
  const hasActivities = activities > 0;

  const docTypes = new Set(documents.map((d) => d.file_type).filter(Boolean));
  const hasDamageReport = docTypes.has("DAMAGE_REPORT");
  const hasJustification = docTypes.has("JUSTIFICATION");
  const hasOrgProfile = !!org?.name;
  const aiDocs = documents.filter((d) => d.source === "ai").length;

  // ── Per-section readiness assessment ───────────────────────────────────
  const sections: SectionReadiness[] = SECTION_DEFS.map((def) => {
    switch (def.key) {
      case "cover-sheet":
        return buildSection(def, {
          sources: compact([
            hasInsuredName && "Insured name",
            hasAddress && "Property address",
            hasCarrier && "Insurance carrier",
            hasPolicyNumber && "Policy number",
            hasDateOfLoss && "Date of loss",
            hasOrgProfile && "Company profile",
          ]),
          missing: compact([
            !hasInsuredName && "Homeowner / insured name",
            !hasAddress && "Property address",
            !hasCarrier && "Insurance carrier",
            !hasPolicyNumber && "Policy number",
            !hasDateOfLoss && "Date of loss",
          ]),
          hasContent: hasInsuredName && hasAddress,
        });

      case "table-of-contents":
        return buildSection(def, {
          sources: ["Auto-generated from section completion"],
          missing: [],
          hasContent: true,
        });

      case "executive-summary":
        return buildSection(def, {
          sources: compact([
            hasWeather && "Weather verification",
            hasAnalyzedPhotos && "YOLO damage detections",
            hasDamageReport && "Damage report",
            hasJustification && "Justification report",
          ]),
          missing: compact([
            !hasWeather && "Weather verification",
            !hasAnalyzedPhotos && "Photo analysis (run detection)",
            !hasDamageReport && "Damage report",
          ]),
          hasContent: hasWeather && hasAnalyzedPhotos,
        });

      case "weather-cause-of-loss":
        return buildSection(def, {
          sources: compact([
            hasWeather && "Weather report fetched",
            hasWeatherNarrative && "AI narrative available",
            hasWeatherEvents && "Storm events mapped",
            hasDateOfLoss && "Date of loss confirmed",
          ]),
          missing: compact([
            !hasWeather && "Run weather verification for this claim",
            !hasDateOfLoss && "Set date of loss on claim",
          ]),
          hasContent: hasWeather,
        });

      case "inspection-overview":
        return buildSection(def, {
          sources: compact([
            hasAddress && "Property address",
            hasProperty && claim?.properties?.roofType && "Roof type",
            hasProperty && claim?.properties?.roofAge && "Roof age",
            hasPhotos && `${photos} photos uploaded`,
          ]),
          missing: compact([
            !hasAddress && "Property address",
            !(hasProperty && claim?.properties?.roofType) && "Roof type (set on property)",
            !hasPhotos && "Upload inspection photos",
          ]),
          hasContent: hasAddress && hasPhotos,
        });

      case "damage-grids":
        return buildSection(def, {
          sources: compact([hasAnalyzedPhotos && `${analyzedPhotos} photos analyzed with YOLO`]),
          missing: compact([
            !hasAnalyzedPhotos && "Run photo analysis to auto-populate damage grids",
            analyzedPhotos < 5 && hasAnalyzedPhotos && "Analyze more photos for better grid data",
          ]),
          hasContent: hasAnalyzedPhotos,
        });

      case "photo-evidence":
        return buildSection(def, {
          sources: compact([
            hasPhotos && `${photos} photos uploaded`,
            hasAnalyzedPhotos && `${analyzedPhotos} analyzed with AI`,
          ]),
          missing: compact([
            !hasPhotos && "Upload claim photos",
            hasPhotos && !hasAnalyzedPhotos && "Run AI analysis on uploaded photos",
          ]),
          hasContent: hasPhotos,
        });

      case "code-compliance":
        return buildSection(def, {
          sources: compact([
            hasCodes && `${codeItems} code requirements loaded`,
            hasAddress && "Property jurisdiction identified",
          ]),
          missing: compact([
            !hasCodes && "Generate code compliance analysis",
            !hasAddress && "Property address needed for jurisdiction",
          ]),
          hasContent: hasCodes,
        });

      case "scope-pricing":
        return buildSection(def, {
          sources: compact([
            hasScope && "Estimate/scope documents present",
            hasAnalyzedPhotos && "AI damage detections for scope",
          ]),
          missing: compact([!hasScope && "Upload or create scope/estimate"]),
          hasContent: hasScope,
        });

      case "repair-justification":
        return buildSection(def, {
          sources: compact([
            hasJustification && "Justification report generated",
            hasAnalyzedPhotos && "YOLO damage evidence",
            hasWeather && "Weather correlation",
          ]),
          missing: compact([
            !hasJustification && "Generate justification report",
            !hasAnalyzedPhotos && "Run photo analysis first",
            !hasWeather && "Run weather verification first",
          ]),
          hasContent: hasJustification,
        });

      case "contractor-summary":
        return buildSection(def, {
          sources: compact([hasOrgProfile && "Company name"]),
          missing: compact([
            !hasOrgProfile && "Complete company profile",
            "License & insurance info (manual entry or org profile)",
          ]),
          hasContent: hasOrgProfile,
        });

      case "timeline":
        return buildSection(def, {
          sources: compact([
            hasDateOfLoss && "Date of loss",
            hasActivities && `${activities} timeline events`,
            hasWeather && "Weather event date",
          ]),
          missing: compact([
            !hasDateOfLoss && "Set date of loss",
            !hasActivities && "No timeline events recorded yet",
          ]),
          hasContent: hasDateOfLoss || hasActivities,
        });

      case "homeowner-statement":
        return buildSection(def, {
          sources: compact([hasInsuredName && "Homeowner identified"]),
          missing: ["Homeowner statement must be provided by the homeowner"],
          hasContent: false, // Always manual
        });

      case "adjuster-cover-letter":
        return buildSection(def, {
          sources: compact([
            hasCarrier && "Insurance carrier identified",
            claim?.adjusterName && "Adjuster name on file",
            hasJustification && "Justification data for letter",
          ]),
          missing: compact([
            !hasCarrier && "Insurance carrier",
            !claim?.adjusterName && "Adjuster name (add to claim)",
          ]),
          hasContent: hasCarrier,
        });

      case "claim-checklist":
        return buildSection(def, {
          sources: ["Auto-derived from section completeness"],
          missing: [],
          hasContent: true,
        });

      case "digital-signatures":
        return buildSection(def, {
          sources: compact([
            hasSignatures && "Signatures on file",
            hasInsuredName && "Homeowner identified for signing",
          ]),
          missing: compact([!hasSignatures && "Collect digital signatures"]),
          hasContent: hasSignatures,
        });

      case "attachments":
        return buildSection(def, {
          sources: compact([
            documents.length > 0 && `${documents.length} documents available`,
            hasPhotos && `${photos} photos`,
          ]),
          missing: [],
          hasContent: documents.length > 0 || hasPhotos,
        });

      default:
        return buildSection(def, {
          sources: [],
          missing: ["Section data source not configured"],
          hasContent: false,
        });
    }
  });

  // ── Scoring (weighted categories — matches calculateReadinessScore) ──
  // Uses the same 7-category weights as folderAssembler so both surfaces
  // show an identical percentage.  Max = 100 (15+20+15+20+15+10+5).
  const catWeather = hasWeatherNarrative ? 15 : hasWeather ? 8 : 0;
  const catPhotos = photos >= 10 ? 20 : photos >= 5 ? 12 : photos >= 1 ? 5 : 0;
  const catCodes = codeItems >= 5 ? 15 : codeItems > 0 ? 8 : 0;
  const catScope = scopeItems > 0 ? (hasAnalyzedPhotos ? 20 : 10) : 0;
  const catNarratives =
    hasJustification && hasDamageReport ? 15 : hasJustification || hasDamageReport ? 8 : 0;
  const catSignatures = signatures >= 2 ? 10 : signatures > 0 ? 5 : 0;
  const catTimeline = activities >= 3 ? 5 : activities > 0 ? 3 : 0;
  const overallScore =
    catWeather + catPhotos + catCodes + catScope + catNarratives + catSignatures + catTimeline;

  // Grade thresholds aligned with calculateReadinessScore
  const overallGrade: ClaimIQReadiness["overallGrade"] =
    overallScore >= 90
      ? "A"
      : overallScore >= 80
        ? "B"
        : overallScore >= 70
          ? "C"
          : overallScore >= 60
            ? "D"
            : "F";

  const requiredSections = sections.filter((s) => s.required);

  const readySections = sections.filter((s) => s.status === "ready").length;
  const partialSections = sections.filter((s) => s.status === "partial").length;
  const missingSections = sections.filter(
    (s) => s.status === "missing" || s.status === "manual"
  ).length;

  // ── Top actions (prioritized) ──────────────────────────────────────────
  const topActions: string[] = [];
  if (!hasPhotos) topActions.push("📸 Upload inspection photos");
  if (hasPhotos && !hasAnalyzedPhotos) topActions.push("🔍 Run AI analysis on photos");
  if (!hasWeather) topActions.push("⛈️ Run weather verification");
  if (hasAnalyzedPhotos && !hasJustification) topActions.push("📋 Generate justification report");
  if (!hasScope) topActions.push("📐 Upload or create scope/estimate");
  if (!hasSignatures) topActions.push("✍️ Collect digital signatures");
  // Always show remaining missing required sections
  for (const s of requiredSections) {
    if (s.status === "missing" && topActions.length < 5) {
      topActions.push(`⚠️ ${s.label}: ${s.nextAction || "Add required data"}`);
    }
  }

  const elapsed = Date.now() - startTime;
  logger.info("[CLAIMIQ] Readiness assessed", {
    claimId,
    score: overallScore,
    grade: overallGrade,
    ready: readySections,
    partial: partialSections,
    missing: missingSections,
    elapsed: `${elapsed}ms`,
  });

  return {
    claimId,
    overallScore,
    overallGrade,
    sections,
    readySections,
    partialSections,
    missingSections,
    topActions: topActions.slice(0, 5),
    layers: {
      vision: { ready: hasAnalyzedPhotos, photoCount: photos, detectionCount: analyzedPhotos },
      weather: { ready: hasWeather, hasVerification: hasWeatherNarrative },
      documentation: { ready: aiDocs > 0, generatedDocs: aiDocs },
      workflow: { ready: hasClaim, claimStatus: claim?.status || "unknown" },
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function buildSection(
  def: (typeof SECTION_DEFS)[number],
  opts: {
    sources: string[];
    missing: string[];
    hasContent: boolean;
  }
): SectionReadiness {
  const { sources, missing, hasContent } = opts;

  let status: SectionStatus;
  let completeness: number;

  if (hasContent && missing.length === 0) {
    status = "ready";
    completeness = 100;
  } else if (hasContent && missing.length > 0) {
    status = "partial";
    completeness = Math.round((sources.length / (sources.length + missing.length)) * 100);
  } else if (!def.canAutoGenerate && !hasContent) {
    status = "manual";
    completeness = 0;
  } else {
    status = "missing";
    completeness =
      sources.length > 0
        ? Math.round((sources.length / (sources.length + missing.length)) * 100)
        : 0;
  }

  const nextAction = missing.length > 0 ? missing[0] : null;

  return {
    key: def.key,
    label: def.label,
    number: def.number,
    required: def.required,
    status,
    completeness,
    availableSources: sources,
    missingItems: missing,
    nextAction,
    canAutoGenerate: def.canAutoGenerate,
    hasExistingContent: hasContent,
  };
}

function compact<T>(arr: (T | false | null | undefined | 0 | "")[]): T[] {
  return arr.filter(Boolean) as T[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Score-Impact Predictor
// ─────────────────────────────────────────────────────────────────────────────

export interface ScoreImpactItem {
  /** The missing item text */
  missingItem: string;
  /** Which section this belongs to */
  sectionKey: string;
  sectionLabel: string;
  /** Current section completeness */
  currentCompleteness: number;
  /** Estimated new section completeness if fixed */
  estimatedCompleteness: number;
  /** Estimated overall score boost (0-100 scale) */
  scoreBoost: number;
  /** Whether this can be auto-fixed by Autopilot */
  canAutoFix: boolean;
  /** Estimated time to fix (minutes) */
  estimatedMinutes: number;
}

/**
 * Predict the score impact of fixing each missing item.
 * Returns items sorted by highest impact first.
 */
export function predictScoreImpacts(readiness: ClaimIQReadiness): ScoreImpactItem[] {
  const totalSections = readiness.sections.length;
  const impacts: ScoreImpactItem[] = [];

  for (const section of readiness.sections) {
    if (section.missingItems.length === 0) continue;

    const totalItems = section.availableSources.length + section.missingItems.length;

    for (const item of section.missingItems) {
      // Estimate: fixing one item adds ~1/totalItems to section completeness
      const itemContribution = totalItems > 0 ? (1 / totalItems) * 100 : 25;
      const newCompleteness = Math.min(100, section.completeness + Math.round(itemContribution));
      const completenessGain = newCompleteness - section.completeness;
      // Impact on overall score: section contributes 1/totalSections of overall
      const scoreBoost = Math.round(completenessGain / totalSections);

      // Auto-fixable heuristic
      const normalizedItem = item.toLowerCase();
      const canAutoFix =
        normalizedItem.includes("weather") ||
        normalizedItem.includes("photo analysis") ||
        normalizedItem.includes("damage report") ||
        normalizedItem.includes("justification") ||
        normalizedItem.includes("code compliance") ||
        normalizedItem.includes("damage grids") ||
        normalizedItem.includes("auto-");

      // Time estimate based on item type
      let estimatedMinutes = 5;
      if (canAutoFix) estimatedMinutes = 1;
      else if (normalizedItem.includes("upload")) estimatedMinutes = 3;
      else if (normalizedItem.includes("signature")) estimatedMinutes = 10;
      else if (normalizedItem.includes("homeowner")) estimatedMinutes = 15;
      else if (normalizedItem.includes("scope") || normalizedItem.includes("estimate"))
        estimatedMinutes = 20;

      impacts.push({
        missingItem: item,
        sectionKey: section.key,
        sectionLabel: section.label,
        currentCompleteness: section.completeness,
        estimatedCompleteness: newCompleteness,
        scoreBoost: Math.max(1, scoreBoost),
        canAutoFix,
        estimatedMinutes,
      });
    }
  }

  return impacts.sort(
    (a, b) => b.scoreBoost - a.scoreBoost || a.estimatedMinutes - b.estimatedMinutes
  );
}
