/**
 * Proposal PDF Renderer — Legacy stub
 * The AI Proposals feature has been removed. This stub prevents build errors
 * for any existing generated_documents of type "PROPOSAL" that need download.
 */
import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40 },
  title: { fontSize: 18, marginBottom: 12, fontWeight: "bold" },
  text: { fontSize: 11, marginBottom: 6, lineHeight: 1.5 },
});

interface ProposalPDFProps {
  data: {
    projectName?: string;
    propertyAddress?: string;
    lossType?: string;
    generatedAt?: string;
    sections?: Array<{ title?: string; content?: string }>;
    totalTokensUsed?: number;
    orgName?: string;
    brandLogoUrl?: string | null;
  };
}

export function ProposalPDFDocument({ data }: ProposalPDFProps) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View>
          <Text style={styles.title}>{data.projectName || "Proposal"}</Text>
          {data.propertyAddress && <Text style={styles.text}>{data.propertyAddress}</Text>}
          {(data.sections || []).map((s, i) => (
            <View key={i}>
              {s.title && <Text style={{ ...styles.text, fontWeight: "bold" }}>{s.title}</Text>}
              {s.content && <Text style={styles.text}>{s.content}</Text>}
            </View>
          ))}
          <Text style={styles.text}>Generated by {data.orgName || "SkaiScraper"}</Text>
        </View>
      </Page>
    </Document>
  );
}
