// lib/intel/automation/executors/supplement.ts
/**
 * 🔥 SUPPLEMENT PACKET EXECUTOR
 * Auto-identifies missing items and builds supplement justification
 */

import { randomUUID } from "node:crypto";

import { buildMasterReportPayload } from "@/lib/intel/master/buildMasterPayload";
import { logger } from "@/lib/logger";
import prisma from "@/lib/prisma";

export async function executeSupplementPacket(claimId: string, orgId: string) {
  logger.debug(`[SKAI] Executing Supplement Packet for ${claimId}`);

  // Build master payload
  const payload = await buildMasterReportPayload({ claimId, orgId });
  const { claim, supplements, damageAssessments } = payload;

  // Collect missing items
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const missingItems: any[] = [];
  if (damageAssessments[0]?.metadata) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const metadata = damageAssessments[0].metadata as any;
    missingItems.push(...(metadata.missingItems || []));
  }

  // Build supplement summary
  const supplementValue = supplements.reduce((sum, s) => sum + s.total, 0);

  const supplementPacket = {
    claimNumber: claim.claimNumber,
    totalValue: supplementValue,
    itemCount: supplements.length,
    missingItems,
    supplements: supplements.map((s) => ({
      id: s.id,
      description: s.description || "Supplement item",
      total: s.total,
      justification: "Required by code/damage findings",
    })),
    generatedAt: new Date().toISOString(),
  };

  // Save to database
  const report = await prisma.ai_reports.create({
    data: {
      id: randomUUID(),
      orgId,
      claimId,
      type: "supplement_packet",
      title: `Supplement Packet - ${claim.claimNumber}`,
      prompt: "Auto-generated by SkaiPDF",
      content: JSON.stringify(supplementPacket),
      model: "gpt-4o",
      userId: "skai",
      userName: "SkaiPDF",
      status: "generated",
      tokensUsed: 0,
      updatedAt: new Date(),
    },
  });

  logger.debug(`[SKAI] Supplement Packet Generated - Total: $${supplementValue}`);

  return {
    reportId: report.id,
    totalValue: supplementValue,
    itemCount: supplements.length,
  };
}
